version: '3.3'
services:
    db:
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - ./sql/set5:/docker-entrypoint-initdb.d
        image: mysql
    front:
        ports:
            - 80
        env_file: .env
        build: .
    adminer:
        ports:
            - 8080
        image: adminer